name: "Wait"
description: "Wait a designated number of milliseconds"
inputs:
  version:
    description: "target version (same as milestone name)"
    required: true
  branch:
    description: "target branch"
    required: true
  token:
    description: "your github token"
    required: true
outputs:
  time: # output will be available to future steps
    description: "The message to output"
runs:
  using: "node12"
  main: "dist/index.js"
