name: generate_release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        default: "v1.0.0"
        required: true

jobs:
  generate:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Generate Release
        run: node dist/index.js
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
          INPUT_BRANCH: ${{ github.head_ref }}
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
